swagger: "2.0"

info:
  version: 1.0.0
  title: WebApp Service API
  description: A description of the WebApp Service API using OpenAPI Specification.

schemes:
  - http

#host: www.example.com
basePath: /api

paths:
  /register:
    post:
      summary: Register a new User.
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: user
          in: body
          description: The user to create.
          schema:
            required:
              - username
              - firstName
              - lastName
              - password
              - passwordConfirm
            properties:
              username:
                type: string
              firstName:
                type: string
              lastName:
                type: string
              password:
                type: string
              passwordConfirm:
                type: string
      responses:
        201:
          description: The user was successfully registered.
          schema:
            required:
              - username
              - firstName
              - lastName
              - bio
              - visible
              - lastSeen
              - token
            properties:
              username:
                type: string
              firstName:
                type: string
              lastName:
                type: string
              bio:
                type: string
              visible:
                type: boolean
              lastSeen:
                type: string
                format: date-time
              token:
                type: string

  /login:
    post:
      summary: Login a User.
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: user
          in: body
          description: The user to create.
          schema:
            required:
              - username
              - password
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        200:
          description: The user was successfully logged in.
          schema:
            required:
              - username
              - firstName
              - lastName
              - bio
              - visible
              - lastSeen
              - token
            properties:
              username:
                type: string
              firstName:
                type: string
              lastName:
                type: string
              bio:
                type: string
              visible:
                type: boolean
              lastSeen:
                type: string
                format: date-time
              token:
                type: string

  /logout:
    delete:
      summary: Logs out a User.
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: user
          in: body
          description: The user to log out.
          schema:
            required:
              - username
              - token
            properties:
              username:
                type: string
              token:
                type: string
      responses:
        200:
          description: The user was successfully logged out.

  /rooms:
    get:
      summary: Retrieves a list of rooms.
      produces:
        - "application/json"
      responses:
        200:
          description: A list of Room
          schema:
            type: array
            items:
              required:
                - name
              properties:
                name:
                  type: string
    post:
      summary: Creates a new room.
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: room
          in: body
          description: The room to create.
          schema:
            required:
              - token
              - name
              - username
            properties:
              token:
                type: string
              name:
                type: string
              username:
                type: string
      responses:
        201:
          description: The room was successfully created.
          schema:
            required:
              - name
            properties:
              name:
                type: string

  /rooms/{name}:
    delete:
      summary: Deletes a room.
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "name"
          in: path
          description: The name of the room to delete.
          required: true
          type: "string"
        - name: room
          in: body
          description: The room to create.
          schema:
            required:
              - token
              - username
            properties:
              token:
                type: string
              username:
                type: string
      responses:
        204:
          description: The room was successfully deleted.
  /rooms/{name}/participations:
    post:
      summary: Creates a new participation.
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "name"
          in: path
          description: The name of the room to in which create the participation.
          required: true
          type: "string"
        - name: participation
          in: body
          description: The user which joins the room.
          schema:
            required:
              - username
              - token
            properties:
              username:
                type: string
              token:
                type: string
      responses:
        201:
          description: The participation was successfully created.
          schema:
            type: object
            required:
              - room
              - user
              - joinDate
            properties:
              room:
                type: object
                required:
                  - name
                properties:
                  name:
                    type: string
              user:
                required:
                  - username
                  - firstName
                  - lastName
                  - bio
                  - visible
                  - lastSeen
                properties:
                  username:
                    type: string
                  firstName:
                    type: string
                  lastName:
                    type: string
                  bio:
                    type: string
                  visible:
                    type: boolean
                  lastSeen:
                    type: string
                    format: date-time
              joinDate:
                type: string
                format: date-time
  /rooms/{name}/participations/{username}:
    delete:
      summary: Deletes a participation.
      produces:
        - "application/json"
      parameters:
        - name: "name"
          in: path
          description: The name of the room in which to delete the participation.
          required: true
          type: "string"
        - name: "username"
          in: path
          description: The user name of the user for which to delete the participation.
          required: true
          type: "string"
        - name: token
          in: body
          description: The token of user who wants to delete the participation.
          schema:
            required:
              - token
            properties:
              token:
                type: string
      responses:
        204:
          description: The participation was successfully deleted.
  /users/{username}:
    delete:
      summary: Deletes a User.
      produces:
        - "application/json"
      parameters:
        - name: "username"
          in: path
          description: The username of the user to delete.
          required: true
          type: "string"
        - name: token
          in: body
          description: The token of user who wants to delete the participation.
          schema:
            required:
              - token
            properties:
              token:
                type: string
      responses:
        204:
          description: The user was successfully delete.
          schema:
            required:
              - username
            properties:
              username:
                type: string

  /users/{username}/participations:
    get:
      summary: Retrieves all the participations for a given user.
      produces:
        - "application/json"
      parameters:
        - name: "name"
          in: path
          description: The name of the room in which to delete the participation.
          required: true
          type: "string"
        - name: "username"
          in: path
          description: The user name of the user for which to delete the participation.
          required: true
          type: "string"
      responses:
        200:
          description: A list of participations.
          schema:
            type: array
            items:
              required:
                - room
              properties:
                room:
                  required:
                    - name
                  properties:
                    name:
                      type: string
